apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- account.yaml
- deployment.yaml
- service.yaml
images:
- name: fluxcd-operator
  newName: ghcr.io/controlplaneio-fluxcd/fluxcd-operator
  newTag: v0.0.1
