# permissions for end users to view fluxinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fluxcd-operator
    app.kubernetes.io/managed-by: kustomize
  name: fluxinstance-viewer-role
rules:
- apiGroups:
  - fluxcd.controlplane.io
  resources:
  - fluxinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fluxcd.controlplane.io
  resources:
  - fluxinstances/status
  verbs:
  - get
