# permissions for end users to edit fluxinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fluxcd-operator
    app.kubernetes.io/managed-by: kustomize
  name: fluxinstance-editor-role
rules:
- apiGroups:
  - fluxcd.controlplane.io
  resources:
  - fluxinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluxcd.controlplane.io
  resources:
  - fluxinstances/status
  verbs:
  - get
