---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - fluxcd.controlplane.io
  resources:
  - fluxinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluxcd.controlplane.io
  resources:
  - fluxinstances/finalizers
  verbs:
  - update
- apiGroups:
  - fluxcd.controlplane.io
  resources:
  - fluxinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fluxcd.controlplane.io
  resources:
  - fluxreports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluxcd.controlplane.io
  resources:
  - fluxreports/finalizers
  verbs:
  - update
- apiGroups:
  - fluxcd.controlplane.io
  resources:
  - fluxreports/status
  verbs:
  - get
  - patch
  - update
