---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - fluxcd.controlplane.io
  resources:
  - fluxinstances
  - fluxreports
  - resourcesetinputproviders
  - resourcesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluxcd.controlplane.io
  resources:
  - fluxinstances/finalizers
  - fluxreports/finalizers
  - resourcesetinputproviders/finalizers
  - resourcesets/finalizers
  verbs:
  - update
- apiGroups:
  - fluxcd.controlplane.io
  resources:
  - fluxinstances/status
  - fluxreports/status
  - resourcesetinputproviders/status
  - resourcesets/status
  verbs:
  - get
  - patch
  - update
