apiVersion: fluxcd.controlplane.io/v1alpha1
kind: FluxInstance
metadata:
  name: flux
spec:
  kustomize:
    patches:
      - patch: |
          - op: replace
            path: /spec/replicas
            value: 0
        target:
          kind: Deployment
