apiVersion: fluxcd.controlplane.io/v1alpha1
kind: FluxInstance
metadata:
  labels:
    app.kubernetes.io/name: fluxcd-operator
    app.kubernetes.io/managed-by: kustomize
  name: fluxinstance-sample
spec:
  # TODO(user): Add fields here
