name: e2e-openshift

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Flux operator strict semver'
        required: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Setup QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - name: Run OLM tests
        run: |
          make test-operatorhub FLUX_OPERATOR_VERSION="${{ github.event.inputs.version }}"
      - name: Run Flux test
        run: |
          kubectl -n flux-system apply -f config/samples/fluxcd_v1_fluxinstance.yaml
          kubectl -n flux-system wait FluxInstance/flux --for=condition=Ready --timeout=5m
