name: Test OperatorHub
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'operator version'
        default: 'v0.3.0'
        required: true

permissions:
  contents: read


jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: write # for pushing and signing container images.
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Setup QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: run tests
        run: |
          make test-operatorhub FLUX_OPERATOR_VERSION="${{ github.event.inputs.version }}"
